name: Test CI

# Quand déclencher la pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # runner fourni par GitHub

    steps:
    - uses: actions/checkout@v3       # récupère ton code
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'       # version Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest             # installe pytest pour tester
    - name: Run tests
      run: |
        pytest -s || echo "No tests yet" # teste le projet


  deploy:
    runs-on: self-hosted
    needs: build      # s'exécute seulement si "test" passe

    steps:
    - uses: actions/checkout@v3

    - name: Simulate deployment
      run: |
        mkdir -p /home/jerome/deploy
        cp calc.py /home/jerome/deploy/
        cp test_calc.py /home/jerome/deploy/
        echo "Deployment completed successfully!"
