name: Test CI

# Quand déclencher la pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # runner fourni par GitHub

    steps:
    - uses: actions/checkout@v3       # récupère ton code
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest             # installe pytest pour tester
    - name: Run tests
      run: |
        pytest -s || echo "No tests yet" # teste le projet


  deploy:
    runs-on: self-hosted
    needs: build      # s'exécute seulement si "test" passe

    steps:
    - uses: actions/checkout@v3

    - name: Simulate deployment
      run: |
        mkdir -p /home/jerome/python-cd/
        cd /home/jerome/python-cd/
        git clone git@github.com:sirLancelot22/python-cicd.git
        echo "Deployment completed successfully!"
